
name: check websites in containers
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    services:
      service1:
        image: docker.io/httpd
        ports:
        - 8081:80
      service2:
        image: docker.io/nginx
        ports:
        - 8082:80
    steps:
      - name: curling first service 
        run: curl http://localhost:8081
      - name: curling second service
        run: | 
          curl http://localhost:8082
          ip a s
